version: "3"

services:
    nginx:
        build: nginx
        image: nginx_revproxy
        container_name: nginx_revproxy1
        environment:
            - NGINX_VERSION=1.13.8-alpine
            - CERTBOT_EMAIL=${CERTBOT_EMAIL}
            - CERTBOT_DOMAIN=${CERTBOT_DOMAIN}
            - CERTBOT_WEBROOT=/usr/share/nginx/html
        volumes:
            - /srv/docker_volumes/letsencrypt:/etc/letsencrypt
        ports:
            - "80:80"
            - "443:443"
        # depends_on:
        #     - owncloud
        restart: always
