version: "3"

services:
    nginx:
        build: nginx
        image: nginx_revproxy
        container_name: nginx_revproxy1
        environment:
            - NGINX_VERSION=1.13.7-alpine
            - CERTBOT_EMAIL=${CERTBOT_EMAIL}
            - CERTBOT_DOMAIN=${CERTBOT_DOMAIN}
            - CERTBOT_WEBROOT=/usr/share/nginx/html
        volumes:
            - /srv/docker_volumes/letsencrypt:/etc/letsencrypt
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - owncloud
        restart: always

    # ampache:
    #     build: ampache
    #     image: ampache_owncloud
    #     container_name: ampache_owncloud1
    #     environment:
    #         - AMPACHE_DB_HOST=mariadb
    #         - AMPACHE_DB_USERNAME=${AMPACHE_DB_USERNAME}
    #         - AMPACHE_DB_PASSWORD=${AMPACHE_DB_PASSWORD}
    #     volumes:
    #         - /srv/docker_volumes/owncloud/files/tony/files/Music:/mnt/owncloud_music
    #         - /srv/docker_volumes/ampache/config:/var/www/config
    #     ports:
    #         - "8080:80"
    #     depends_on:
    #         - owncloud
    #     restart: always

    owncloud:
        # build:
        #     context: owncloud
        #     args:
        #         - OWNCLOUD_VERSION=${OWNCLOUD_VERSION}
        # image: owncloud_server
        image: owncloud/server:10.0.3-apache
        container_name: owncloud_server1
        environment:
            - OWNCLOUD_VERSION=10.0.3-apache
            - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}
            - OWNCLOUD_ADMIN_USERNAME=${OWNCLOUD_ADMIN_USERNAME}
            - OWNCLOUD_ADMIN_PASSWORD=${OWNCLOUD_ADMIN_PASSWORD}
            - OWNCLOUD_HTTP_PORT=80
            - OWNCLOUD_HTTPS_PORT=443
            - OWNCLOUD_DB_TYPE=mysql
            - OWNCLOUD_DB_HOST=mariadb
            - OWNCLOUD_DB_NAME=owncloud
            - OWNCLOUD_DB_USERNAME=${OWNCLOUD_DB_USERNAME}
            - OWNCLOUD_DB_PASSWORD=${OWNCLOUD_DB_PASSWORD}
            - OWNCLOUD_UTF8MB4_ENABLED=true
            - OWNCLOUD_REDIS_ENABLED=true
            - OWNCLOUD_REDIS_HOST=redis
        volumes:
            - /srv/docker_volumes/owncloud:/mnt/data
        depends_on:
            - mariadb
            - redis
        # healthcheck:
        #     test: ["CMD", "curl", "-f", "http://localhost:80/status.php"]
        #     interval: 30s
        #     timeout: 10s
        #     retries: 5
        restart: always

    mariadb:
        # build: mariadb
        # image: owncloud_mariadb
        image: webhippie/mariadb:latest
        container_name: owncloud_mariadb1
        environment:
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
            - MARIADB_DATABASE=owncloud
            - MARIADB_USERNAME=${MARIADB_USERNAME}
            - MARIADB_PASSWORD=${MARIADB_PASSWORD}
            - MARIADB_MAX_ALLOWED_PACKET=128M
            - MARIADB_INNODB_LOG_FILE_SIZE=64M
            - MARIADB_INNODB_LARGE_PREFIX=ON
            - MARIADB_INNODB_FILE_FORMAT=Barracuda
        volumes:
            - /srv/docker_volumes/mysql:/var/lib/mysql
        # healthcheck:
        #     test: ["CMD", "/usr/bin/healthcheck"]
        #     interval: 30s
        #     timeout: 10s
        #     retries: 5
        restart: always

    redis:
        # build: redis
        # image: owncloud_redis
        image: webhippie/redis:latest
        container_name: owncloud_redis1
        volumes:
            - /srv/docker_volumes/redis:/var/lib/redis
        # healthcheck:
        #     test: ["CMD", "/usr/bin/healthcheck"]
        #     interval: 30s
        #     timeout: 10s
        #     retries: 5
        restart: always
